config/routes.rb
Rails.application.routes.draw do
  root "animals#index"
  resources :animals
  resources :sightings
  resources :regions 
  get "/search_region", to: "regions#search_region"
  get "/new_search", to: "sightings#new_search"
  get "/search_date", to: "sightings#search_date"

  get '/regions/:id/new_sightings', to: 'regions#new_sighting', as: "region_new_sighting"
  post '/regions/:id/sightings', to: 'regions#create_sighting', as: "region_create_sighting"

  get '/animals/:id/new_sightings', to: 'animals#new_sighting', as: "animal_new_sighting"
  post '/animals/:id/sightings', to: 'animals#create_sighting', as: "animal_create_sighting"
end

app/models/animal.rb
class Animal < ApplicationRecord
    has_many :sightings, class_name: 'Sighting', dependent: :destroy
    has_many :regions, through: :sightings, dependent: :destroy, class_name: 'Region'

    validates :name, presence: true 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :sightings, class_name: 'Sighting', dependent: :destroy 
    has_many :animals, through: :sightings, dependent: :destroy, class_name: 'Animal'

    validates :region, presence: true 
end

app/models/sighting.rb
class Sighting < ApplicationRecord
    belongs_to :animal, class_name: "Animal", foreign_key: "animal_id"
    belongs_to :region, class_name: "Region", foreign_key: "region_id"
    
    validates :long, presence: true 
    validates :longs, presence: true 
    validates :lat, presence: true 
    validates :lats, presence: true 
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all 
  end
    
  def show 
    @animal = Animal.find(params[:id])
  end 
    
  def new 
    @animal = Animal.new
  end 
    
  def create
    @animal = Animal.find_or_create_by(animal_params)
    
    if @animal.save 
      flash[:success] = "New Animal successfully created!"
      redirect_to animal_path(@animal)
    else 
      flash.now[:error] = "New Animal creation failed!"
      render :new 
    end  
  end
    
  def edit 
    @animal = Animal.find(params[:id])
  end 
    
  def update 
    @animal = Animal.find(params[:id])
    
    if @animal.update(animal_params)
      redirect_to @animal 
    else 
      render :edit 
    end 
  end 
    
  def destroy 
    @animal = Animal.find(params[:id])
    @animal.destroy
        
    redirect_to root_path 
  end 

  def new_sighting 
    @animal = Animal.find(params[:id])
  end 

  def create_sighting 
    @animal = Animal.find(params[:id])
    @region = Region.find(params[:region_id])
    @sighting = Sighting.new(region: @region, animal: @animal, long: long, lat: lat, longs: longs, lats: lats)

    if @sighting.save
      flash[:success] = "New Sighting successfully created!"
      redirect_to sighting_path(@sighting)
    else 
      flash.now[:error] = "New Sighting creation failed!"
      render :new_sighting
    end 
  end 
    
  private 
  def animal_params 
    params.require(:animal).permit(:name, :animal_id)
  end 

  def long
    params[:long]
  end 

  def longs
    params[:longs]
  end 

  def lat
    params[:lat]
  end 

  def lats
    params[:lats]
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
    def index
        @regions = Region.all
    end
    
    def show 
        @region = Region.find(params[:id])
    end 
    
    def new 
        @region = Region.new
    end 
    
    def create 
        @region = Region.new(region_params)
    
        if @region.save
            flash[:success] = "New Region successfully created!"
            redirect_to @region 
        else 
            flash.now[:error] = "New Region creation failed!"
            render :new 
        end 
    end 
    
    def edit 
        @region = Region.find(params[:id])
    end 
    
    def update 
        @region = Region.find(params[:id])
    
        if @region.update(region_params)
            redirect_to @region
        else 
            render :edit 
        end 
    end 
    
    def destroy 
        @region = Region.find(params[:id])
        @region.destroy
    
        redirect_to root_path
    end

    def new_sighting
        @region = Region.find(params[:id])
    end 
    
    def create_sighting 
        @region = Region.find(params[:id])
        @animal = Animal.find(params[:animal_id])
        @sighting = Sighting.new(region: @region, animal: @animal, long: long, lat: lat, longs: longs, lats: lats)
    
        if @sighting.save
            flash[:success] = "New Sighting successfully created!"
            redirect_to sighting_path(@sighting)
        else 
            flash.now[:error] = "New Sighting creation failed!"
            render :new_sighting
        end 
    end 

    def search_region
        @animals = Animal.joins(:region).where("regions.region LIKE ?", params[:search_by_region])
    end 
    
    private 
    def region_params
        params.require(:region).permit(:region)
    end 

    def long
        params[:long]
    end 

    def longs
        params[:longs]
    end 

    def lat
        params[:lat]
    end 

    def lats
        params[:lats]
    end 
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
    def index
        @sightings = Sighting.all
    end
    
    def show 
        @sighting = Sighting.find(params[:id])
    end 
    
    def new 
        @sighting = Sighting.new
    end 
    
    def create 
        @region = Region.find_by(params[:id])
        @animal = Animal.find_by(params[:id])
        @sighting = Sighting.create(sighting_params)

        if @sighting.save
            flash[:success] = "New Sighting successfully created!"
            redirect_to sighting_path(@sighting)
        else 
            flash.now[:error] = "New Sighting creation failed!"
            render :new 
        end 
    end 
    
    def edit 
        @sighting = Sighting.find(params[:id])
    end 
    
    def update 
        @sighting = Sighting.find(params[:id])
    
        if @sighting.update(sighting_params)
          redirect_to @sighting 
        else 
          render :edit 
        end 
    end 
    
    def destroy 
        @sighting = Sighting.find(params[:id])
        @sighting.destroy 
    
        redirect_to root_path
    end 

    def new_search
    end 

    def search_date
        @sightings = Sighting.where("created_at LIKE ?", params[:search_by_date])
    end 
    
    private 
    def sighting_params 
      params.require(:sighting).permit( :long, :longs, :lat, :lats, :animal_id, :region_id)
    end 
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/_form.html.slim
div 
    =form_with model: @animal do |form|

        =form.label :Animal
        =form.text_field :name 
            -@animal.errors.full_messages_for(:name).each do |message|
                =message 

        br

        =form.submit

app/views/animals/edit.html.slim
h1 
    | Edit Animal 

=render "form", animal: @animal 

app/views/animals/index.html.slim
h1 
    | Animals 

-@animals.each do |animal|
    ul
        =link_to animal.name, animal 

br 

=link_to "Add Animal", new_animal_path 
br
=link_to "Regions", regions_path 
br 
=link_to "All Sightings", sightings_path 

app/views/animals/new.html.slim
h1 
    | New Animal 

=render "form", animal: @animal 

app/views/animals/new_sighting.html.slim
h1 
    | Add sighting for 
    =@animal.name 

=form_with url: animal_create_sighting_path, method: :post do |form|

    =form.label "Animal: "
    =form.label " #{@animal.name}"

    br

    =form.label "Region"
    =form.select :region_id, Region.all.collect { |region| [region.region, region.id] }, include_blank: true 

    br 

    =form.label "Longitude Degree" 
    =form.text_field :long
        -@sighting.errors.full_messages_for(:long).each do |message|
            =message 
    =form.label "Longitude Direction"
    =form.text_field :longs
        -@sighting.errors.full_messages_for(:longs).each do |message|
            =message 
    br

    =form.label "Lattitude Degree" 
    =form.text_field :lat
        -@sighting.errors.full_messages_for(:lat).each do |message|
            =message 
    =form.label "Lattitude Direction"
    =form.text_field :lats
        -@sighting.errors.full_messages_for(:lats).each do |message|
            =message 
    br
    =form.submit

app/views/animals/show.html.slim
h1 
    = @animal.name 

p 
    
    -@animal.sightings.each do |sighting|
        ul  
            =sighting.region.region
            |  |
            =link_to sighting.created_at.strftime("%Y-%b-%d"), sighting

br 
=link_to "Add sighting for #{@animal.name}", animal_new_sighting_path(animal_id: @animal)
br 
=link_to "Edit Animal", edit_animal_path(@animal)
br
=link_to "Delete this animal", animal_path(@animal), method: :delete, data: { confirm: "Are you sure?"}
br 
=link_to "Return to Animals", animals_path 
br 
=link_to "Home", root_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= flash[:success] %>
    <%= flash[:error] %>

    <%= yield %>
  </body>
</html>

app/views/regions/_form.html.slim
div 
    =form_with model: @region do |form|

        =form.label :Region
        =form.text_field :region
            -@region.errors.full_messages_for(:region).each do |message|
                =message 

        br

        =form.submit

app/views/regions/edit.html.slim
h1 
    | Edit Region 

=render "form", region: @region 

app/views/regions/index.html.slim
h1 
    | Regions

-@regions.each do |region|
    ul
        =link_to region.region, region
br 

=link_to "Add Region", new_region_path 
br
=link_to "Animals", animals_path 
br 
=link_to "Home", root_path 
br
h2 
    | Search by Region 
= form_with  url:"/search_region", method: :get do |form| 
    =form.label :search_by_region
    =form.text_field :search_by_region
    =form.submit "Search"

app/views/regions/new.html.slim
h1 
    | New Region 

=render "form", region: @region 

app/views/regions/new_sighting.html.slim
h1 
    | Add sighting for 
    =@region.region 

div 
    =form_with url: region_create_sighting_path, method: :post do |form|

        =form.label "Region: "
        =form.label " #{@region.region.capitalize}"
        =hidden_field_tag :region_id, @region.id

        br

        =form.label "Animal"
        =form.select :animal_id, Animal.all.collect { |animal| [animal.name, animal.id] }, include_blank: true 

        br

        =form.label "Longitude Degree " 
        =form.text_field :long
            -@sighting.errors.full_messages_for(:long).each do |message|
                =message 
        =form.label " Longitude Direction "
        =form.text_field :longs
            -@sighting.errors.full_messages_for(:longs).each do |message|
                =message 
        br

        =form.label "Lattitude Degree " 
        =form.text_field :lat
            -@sighting.errors.full_messages_for(:lat).each do |message|
                =message 
        =form.label " Lattitude Direction "
        =form.text_field :lats
            -@sighting.errors.full_messages_for(:lats).each do |message|
                =message 
        br

        =form.submit

app/views/regions/search_region.html.slim
h1 
    |Search Results 

    br 

-if @animals.present?
    -@animals.each do |animal|
        ul
            =animal.name 
            br
-else
        | No results found

br
br 
=link_to "Home", root_path 

app/views/regions/show.html.slim
h1 
    =@region.region
p 
    -@region.animals.each do |animal|
        ul
            =link_to animal.name, animal

 
=link_to "Add sighting for #{@region.region}", region_new_sighting_path(region_id: @region)
br
=link_to "Edit Region", edit_region_path(@region)
br
=link_to "Delete this Region", region_path(@region),
                    method: :delete,
                    data: { confirm: "Are you sure?"}
br
=link_to "Regions", regions_path 
br
=link_to "Home", root_path

app/views/sightings/_form.html.slim
div 
    =form_with model: @sighting do |form|

        =form.label "Animal"
        =form.select :animal_id, Animal.all.collect { |animal| [animal.name, animal.id] }, include_blank: true

        br

        =form.label "Date"
        =form.date_field :date
            -@sighting.errors.full_messages_for(:date).each do |message|
                =message 

        br

        =form.label "Longitude Degree" 
        =form.text_field :long
            -@sighting.errors.full_messages_for(:long).each do |message|
                =message 
        =form.label "Longitude Direction"
        =form.text_field :longs
            -@sighting.errors.full_messages_for(:longs).each do |message|
                =message 
        br

        =form.label "Lattitude Degree" 
        =form.text_field :lat
            -@sighting.errors.full_messages_for(:lat).each do |message|
                =message 
        =form.label "Lattitude Direction"
        =form.text_field :lats
            -@sighting.errors.full_messages_for(:lats).each do |message|
                =message 
        br

        =form.submit

app/views/sightings/edit.html.slim
h1 
    | Edit Sighting

=render "form", sighting: @sighting

app/views/sightings/index.html.slim
h1 
    | All sightings 


-@sightings.each do |sighting|
    ul
        =link_to sighting.created_at.strftime("%Y-%b-%d"), sighting
br 
=link_to "Add Sighting", new_sighting_path
br
=link_to "Search for sighting", new_search_path
br 
=link_to "Home", root_path 

app/views/sightings/new.html.slim
h1 
    | New Sighting

=render "form", sighting: @sighting 

app/views/sightings/new_search.html.slim
h1 
    | Search for sighting by date 

= form_with  url:"/search_date", method: :get do |form| 
    =form.label :search_by_date
    =form.date_field :search_by_date
    =form.submit "Search"

app/views/sightings/search_date.html.slim
h1 
    |Search Results 

    br 

-if @sightings.present?
    -@sightings.each do |sighting|
        ul
            =sighting.region.region
            | , 
            =sighting.animal.name 
            | , 
            =sighting.created_at
            | , 
            =sighting.long 
            |  
            =sighting.longs
            | , 
            =sighting.lat 
            |  
            =sighting.lats

            br
-else
        | No results found

br
br
=link_to "Home", root_path 

app/views/sightings/show.html.slim
h1 
    =@sighting.region.region
    |, 
    =@sighting.animal.name 
    | , 
    =@sighting.created_at.strftime("%Y-%b-%d")
    | , 
    =@sighting.long 
    |  
    =@sighting.longs
    | , 
    =@sighting.lat 
    |  
    =@sighting.lats

br    

=link_to "Edit sighting", edit_sighting_path(@sighting)
br
=link_to "Delete this sighting", sighting_path(@sighting),
                    method: :delete,
                    data: { confirm: "Are you sure?"}
br
=link_to "Return to Sightings", sightings_path
br 
=link_to "Home", root_path